# Generated by Django 5.1.4 on 2025-01-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(
                blank=True,
                help_text="Введите URL видео",
                max_length=255,
                null=True,
                verbose_name="Видео",
            ),
        ),
    ]
